"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*x!i54jqz1dn)q0c@04v!+87ojbj$^jf_wj6kgv!0305i0k=y!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

USE_FAKE_SELLER = True

WSGI_APPLICATION = 'backend.wsgi.application'

CORS_ALLOW_ALL_ORIGINS = True

# CORS_ALLOWED_ORIGINS = [
#    "http://localhost:3000",
# ]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

MIDDLEWARE = ['corsheaders.middleware.CorsMiddleware', *MIDDLEWARE]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # آدرس Vite
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


from datetime import timedelta

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": "your-secret-key",  # می‌تونی از SECRET_KEY جنگو استفاده کنی
    "AUTH_HEADER_TYPES": ("Bearer",),
}





EDA_CARD_ANALYSIS_PROMPTS = {
    "real_profit": (
        "You are Predify, an economic assistant for Digikala sellers.\n"
        "Analyze this product’s real profit margin after commission and costs.\n"
        "Write a concise and practical insight (max 80 words).\n"
        "Focus on: overall profitability, key risks, and one actionable suggestion.\n"
        "Please create your advice in only 50 words"
        "DATA:\n{data}"
    ),

    "slow_movers": (
        "You are an inventory and pricing strategist.\n"
        "Analyze the slow-moving product below.\n"
        "Please create your advice in only 50 words"
        "Write a short, actionable summary (max 80 words) explaining:\n"
        "- Why this SKU is slow\n"
        "- Financial risk\n"
        "- Whether discount/removal is wise\n"
        "- One practical action for improvement\n"
        "DATA:\n{data}"
    ),

    "breakeven": (
        'You are an economic advisor evaluating breakeven status.\n'
        "Please create your advice in only 50 words"
        "Explain in under 80 words:\n"
        "- How far the product is from breakeven\n"
        "- What this means financially\n"
        "- What lever(s) seller can pull (price, cost, volume)\n"
        "Be clear and practical.\n"
        "DATA:\n{data}"
    ),

    "golden_times": (
        "Please create your advice in only 50 words"
        "You are analyzing sales timing patterns.\n"
        "Using the data, explain (max 80 words):\n"
        "- The strongest daily/hourly windows\n"
        "- When promotions perform best\n"
        "- One recommendation for scheduling ads or discounts\n"
        "DATA:\n{data}"
    ),

    "revenue_forecast": (
        "You are an economic forecasting assistant.\n"
        "Please create your advice in only 50 words"

        "Provide a short insight (max 80 words) about:\n"
        "- Expected revenue trend\n"
        "- Stability of recent sales\n"
        "- Whether forecast shows growth/decline\n"
        "- A practical strategic action\n"
        "DATA:\n{data}"
    ),

    "discount_vs_competitors": (
        "You are a pricing analyst.\n"
        "Please create your advice in only 50 words"
        "Compare this product’s effective discount and final price against competitors.\n"
        "In max 80 words, summarize:\n"
        "- The price position\n"
        "- Whether seller is competitive\n"
        "- A suggested action (raise/lower price or maintain)\n"
        "DATA:\n{data}"
    ),

    "restock": (
        "You are an inventory planner.\n"
        "Please create your advice in only 50 words"
        "Using the data, write a concise insight (max 80 words):\n"
        "- Risk of stockout\n"
        "- Whether restocking is urgent\n"
        "- Suggested reorder quantity/timing\n"
        "DATA:\n{data}"
    ),

    "speed_comparison": (
        "You are comparing old vs new product sales speed.\n"
        "Please create your advice in only 50 words"
        "Write a short insight (max 80 words) explaining:\n"
        "- Whether the new product performs better or worse\n"
        "- Possible causes\n"
        "- One practical improvement suggestion\n"
        "DATA:\n{data}"
    ),

    "comments_analysis": (
        "You are an assistant analyzing customer sentiments.\n"
        "Please create your advice in only 50 words"
        "In no more than 80 words, summarize:\n"
        "- Key sentiment trends\n"
        "- Main problems or praises\n"
        "- One practical action for product or service improvement\n"
        "DATA:\n{data}"
    ),
}
