# Generated by Django 5.2.8 on 2025-11-17 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_cost_pct', models.FloatField(default=10.0)),
                ('slow_mover_min_speed', models.FloatField(default=1.0)),
                ('slow_mover_min_margin', models.FloatField(default=10.0)),
                ('lead_time_days', models.IntegerField(default=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
